### PR TITLE
Issue 16 in BQ date should be compared to date

### LINKED ISSUE #16: 'dates' model produces error on BigQuery
#### Issue description

Compiled SQL for 'dates' model in dbt-date version 0.2.4 is invalid within BigQuery. ```dbt run``` will fail for any BigQuery project which includes this package directly or indirectly (e.g. through dbt-expectations, which is how this bug was discovered in our environment). Since dbt-expectations pulls in the most recent dbt-date 0.2.* version with each invocation of ```dbt deps```, this failing model was introduced into our production deployment without any code changes on our behalf.

#### Environment description

- dbt version: 0.18.1
- dbt-date version: 0.2.4
- database: BigQuery

#### Steps to reproduce the issue

1.  ```dbt deps```
2.  ```dbt run -m dates```

#### What's the expected result?

Model run passes

#### What's the actual result?

```
Completed with 1 error and 0 warnings:
Database Error in model dates (models/example_models/dates.sql)
  No matching signature for operator <= for argument types: DATETIME, TIMESTAMP. Supported signature: ANY <= ANY at [160:11]
  compiled SQL at target/run/dbt_date/models/example_models/dates.sql
```

#### Additional details / screenshot

I suspect that the issue stems from the commit https://github.com/calogica/dbt-date/commit/709f7f649670665700e4e2610460ff0de382eddd

### PR DESCRIPTION
**Pull request by VasiliiSurov**
Adding BigQuery specific macros get_base_dates

### CODE REVIEW

File: macros/get_base_dates.sql [hunk 1]
```diff
@@ -1,4 +1,8 @@
 {% macro get_base_dates(start_date=None, end_date=None, n_dateparts=None, datepart=None) %}
+    {{ adapter.dispatch('get_base_dates', packages = dbt_date._get_utils_namespaces()) (start_date, end_date) }}
```
Comment (clausherther) [inline macros/get_base_dates.sql]: Hi @VasiliiSurov, love the adapter macro version here, but I think you need to also pass the additional parameters like `n_dateparts` and `datepart` to the call to `dispatch` and also the subsequent macros it's calling, right?

File: macros/get_base_dates.sql [hunk 2]
```diff
@@ -1,4 +1,8 @@
...
+{% endmacro %}
+
+{% macro default__get_base_dates(start_date, end_date) %}
```
Comment (clausherther) [inline macros/get_base_dates.sql]: I think you also need `n_dateparts, datepart` here

File: macros/get_base_dates.sql [hunk 3]
```diff
@@ -23,4 +27,31 @@ select
     cast(d.date_day as date) as date_day
 from
     date_spine d
-{% endmacro %}
\ No newline at end of file
+{% endmacro %}
+
+{% macro bigquery__get_base_dates(start_date, end_date) %}
```
Comment (clausherther) [inline macros/get_base_dates.sql]: I think you also need `n_dateparts, datepart` here

**Review by clausherther — CHANGES_REQUESTED** [review]
Thanks for this @VasiliiSurov, helps a lot! I made a couple of comments where we need to add some params but then I think this might be good to go!

**Comment by VasiliiSurov** [comment]
@clausherther 
totally make sense, I didn't use these params so they felt out from my attention

File: macros/get_base_dates.sql [hunk 4]
```diff
@@ -1,4 +1,8 @@
 {% macro get_base_dates(start_date=None, end_date=None, n_dateparts=None, datepart=None) %}
+    {{ adapter.dispatch('get_base_dates', packages = dbt_date._get_utils_namespaces()) (start_date, end_date, n_dateparts, datepart) }}
+{% endmacro %}
+
+{% macro default__get_base_dates(start_date=None, end_date=None, n_dateparts=None, datepart=None) %}
```
Comment (clausherther) [inline macros/get_base_dates.sql]: Thanks for adding those params! 
Sorry, one more nitpick: the `default__get_base_dates` and `bigquery__get_base_dates` macros don't need the `None` default parameter values since this get passed in from the dispatch. I'd like to leave those out so we can change the default parameters at the entry point macro without having to change them everywhere else. Thanks!

**Review by clausherther — CHANGES_REQUESTED** [review]
Minor change and then I think we're good to go!

**Comment by VasiliiSurov** [comment]
@clausherther 
Done

**Review by clausherther — APPROVED** [review]
Looks good, thanks! 👍
