### PR TITLE
simplify shimming

### LINKED ISSUE #25: what week of year is December 1, 2020?
Feeling like a crazy person trying to resolve the newly broken test in https://github.com/dbt-msft/tsql-utils/pull/45.

```yml
- dbt_utils.expression_is_true:
    expression: "week_of_year = {{ dbt_date.week_of_year('date_day') }}" 
```

What _should_ the week of year be for `2020-12-01`? the `default__get_test_dates()` says is it 48, but TSQL says otherwise despite `datepart` providing a `week` and `isoweek` see [docs](https://docs.microsoft.com/en-us/sql/t-sql/functions/datepart-transact-sql?view=sql-server-ver15)

```sql
SELECT
    datepart(week, CAST('2020-12-01' as date)) as week_of_year,
    datepart(iso_week, CAST('2020-12-01' as date)) as iso_week_of_year
```

| week_of_year | iso_week_of_year |
| -------------- | ------------------ |
|49 | 49 |

interestingly, in @b-per's fork's [`week_of_year()`](https://github.com/b-per/dbt-date-tsql/blob/ed5401cfe257e97a5c17a57072006edeba6820ca/macros/dbt_date/calendar_date/week_of_year.sql#L1-L3) he subtracts a day, ostensibly just to get the test to pass...

```sql
{%- macro sqlserver__week_of_year(date) -%}
cast({{ dbt_date.date_part('week', dbt_utils.dateadd('day',-1,date)) }} as {{ dbt_utils.type_int() }})
{%- endmacro %}
```

### PR DESCRIPTION
**Pull request by dataders**
### high-level summary
- refactored `get_test_dates()` in order to:
    - more surgically change behavior, and
    -  keep shimmed macros more in line w/ dbt-date's integration tests as they update.
- deleted `dbt_date_integration_tests`'s `_get_utils_namespaces()` to align with `dbt-utils`'s strategy of joining integration test macros to the dispatch list. (note: this will certainly change with `v0.20.0`, but at least it's a step in the right direction. 

### detail

resolves: #25
given that the only difference in `get_test_dates()` is the `week_of_year` column, this will make it easier to shim.

once this merges, making `get_test_dates()` working for TSQL will be as simple as adding this macro to the `tsql-utils` dbt-date integration tests macros folder (see: https://github.com/dbt-msft/tsql-utils/pull/48)

```
{% macro sqlserver__get_test_week_of_year() -%}
    {{ log("in the right macro!", info=True) }}
    {# who knows what T-SQL uses?! #}
    {# see: https://github.com/calogica/dbt-date/issues/25 #}
    {{ return([49,49]) }}
{%- endmacro %}

{% macro synapse__get_test_week_of_year() -%}
     {{ return(sqlserver__get_test_week_of_year()) }}
{%- endmacro %}
```

### CODE REVIEW

File: integration_tests/macros/get_test_dates.sql [hunk 1]
```diff
@@ -37,56 +33,26 @@ select
...
+    {{ return(adapter.dispatch('get_test_week_of_year', packages = dbt_date._get_utils_namespaces()) ()) }}
+{%- endmacro %}
 
-    cast('2020-11-30' as date) as iso_week_start_date,
-    cast('2020-12-06' as date) as iso_week_end_date,
-    49 as iso_week_of_year,
-    'December' as month_name,
-    'Dec' as month_name_short
+{% macro default__get_test_week_of_year() -%}
+    {{ log("in default macro", info=True) }}
```
Comment (clausherther) [inline integration_tests/macros/get_test_dates.sql]: We should probably remove this log() statement

File: integration_tests/macros/get_test_dates.sql [hunk 2]
```diff
@@ -37,56 +33,26 @@ select
...
-    'Tue' as day_name_short,
-    1 as day_of_month,
-    3 as day_of_week,
-    2 as iso_day_of_week,
-    336 as day_of_year,
-    cast('2020-11-29' as date) as week_start_date,
-    cast('2020-12-05' as date) as week_end_date,
-    -- Snowflake returns ISO week numbers with the standard config
-    49 as week_of_year,
+{% macro get_test_week_of_year() -%}
```
Comment (clausherther) [inline integration_tests/macros/get_test_dates.sql:44]: I think this works for now, although this seems a bit harder to follow for anyone new than simply having a separate test dataset for each platform.

**Review by clausherther — APPROVED** [review]
👍

File: integration_tests/macros/get_test_dates.sql (hunk 1 above)
Comment (dataders) [reply integration_tests/macros/get_test_dates.sql]: whoops good catch. I'll fix that in another PR

Comment (clausherther) [reply integration_tests/macros/get_test_dates.sql]: Don't worry, I removed it and merged this
